/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlansIndexRouteImport } from './routes/plans/index'
import { Route as PlansPlanIdRouteImport } from './routes/plans/$planId'
import { Route as PlansPlanIdIndexRouteImport } from './routes/plans/$planId/index'
import { Route as PlansPlanIdObjectivesRouteImport } from './routes/plans/$planId/objectives'
import { Route as PlansPlanIdObjectivesOverviewRouteImport } from './routes/plans/$planId/objectives/overview'
import { Route as PlansPlanIdObjectivesAnalyticsRouteImport } from './routes/plans/$planId/objectives/analytics'
import { Route as PlansPlanIdObjectivesActivityRouteImport } from './routes/plans/$planId/objectives/activity'
import { Route as PlansPlanIdObjectivesObjectiveIdRouteImport } from './routes/plans/$planId/objectives/$objectiveId'
import { Route as PlansPlanIdObjectivesOverviewIndexRouteImport } from './routes/plans/$planId/objectives/overview/index'
import { Route as PlansPlanIdObjectivesOverviewObjectiveIdRouteImport } from './routes/plans/$planId/objectives/overview/$objectiveId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansIndexRoute = PlansIndexRouteImport.update({
  id: '/plans/',
  path: '/plans/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansPlanIdRoute = PlansPlanIdRouteImport.update({
  id: '/plans/$planId',
  path: '/plans/$planId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansPlanIdIndexRoute = PlansPlanIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlansPlanIdRoute,
} as any)
const PlansPlanIdObjectivesRoute = PlansPlanIdObjectivesRouteImport.update({
  id: '/objectives',
  path: '/objectives',
  getParentRoute: () => PlansPlanIdRoute,
} as any)
const PlansPlanIdObjectivesOverviewRoute =
  PlansPlanIdObjectivesOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => PlansPlanIdObjectivesRoute,
  } as any)
const PlansPlanIdObjectivesAnalyticsRoute =
  PlansPlanIdObjectivesAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => PlansPlanIdObjectivesRoute,
  } as any)
const PlansPlanIdObjectivesActivityRoute =
  PlansPlanIdObjectivesActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => PlansPlanIdObjectivesRoute,
  } as any)
const PlansPlanIdObjectivesObjectiveIdRoute =
  PlansPlanIdObjectivesObjectiveIdRouteImport.update({
    id: '/$objectiveId',
    path: '/$objectiveId',
    getParentRoute: () => PlansPlanIdObjectivesRoute,
  } as any)
const PlansPlanIdObjectivesOverviewIndexRoute =
  PlansPlanIdObjectivesOverviewIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PlansPlanIdObjectivesOverviewRoute,
  } as any)
const PlansPlanIdObjectivesOverviewObjectiveIdRoute =
  PlansPlanIdObjectivesOverviewObjectiveIdRouteImport.update({
    id: '/$objectiveId',
    path: '/$objectiveId',
    getParentRoute: () => PlansPlanIdObjectivesOverviewRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/plans/$planId': typeof PlansPlanIdRouteWithChildren
  '/plans': typeof PlansIndexRoute
  '/plans/$planId/objectives': typeof PlansPlanIdObjectivesRouteWithChildren
  '/plans/$planId/': typeof PlansPlanIdIndexRoute
  '/plans/$planId/objectives/$objectiveId': typeof PlansPlanIdObjectivesObjectiveIdRoute
  '/plans/$planId/objectives/activity': typeof PlansPlanIdObjectivesActivityRoute
  '/plans/$planId/objectives/analytics': typeof PlansPlanIdObjectivesAnalyticsRoute
  '/plans/$planId/objectives/overview': typeof PlansPlanIdObjectivesOverviewRouteWithChildren
  '/plans/$planId/objectives/overview/$objectiveId': typeof PlansPlanIdObjectivesOverviewObjectiveIdRoute
  '/plans/$planId/objectives/overview/': typeof PlansPlanIdObjectivesOverviewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/plans': typeof PlansIndexRoute
  '/plans/$planId/objectives': typeof PlansPlanIdObjectivesRouteWithChildren
  '/plans/$planId': typeof PlansPlanIdIndexRoute
  '/plans/$planId/objectives/$objectiveId': typeof PlansPlanIdObjectivesObjectiveIdRoute
  '/plans/$planId/objectives/activity': typeof PlansPlanIdObjectivesActivityRoute
  '/plans/$planId/objectives/analytics': typeof PlansPlanIdObjectivesAnalyticsRoute
  '/plans/$planId/objectives/overview/$objectiveId': typeof PlansPlanIdObjectivesOverviewObjectiveIdRoute
  '/plans/$planId/objectives/overview': typeof PlansPlanIdObjectivesOverviewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/plans/$planId': typeof PlansPlanIdRouteWithChildren
  '/plans/': typeof PlansIndexRoute
  '/plans/$planId/objectives': typeof PlansPlanIdObjectivesRouteWithChildren
  '/plans/$planId/': typeof PlansPlanIdIndexRoute
  '/plans/$planId/objectives/$objectiveId': typeof PlansPlanIdObjectivesObjectiveIdRoute
  '/plans/$planId/objectives/activity': typeof PlansPlanIdObjectivesActivityRoute
  '/plans/$planId/objectives/analytics': typeof PlansPlanIdObjectivesAnalyticsRoute
  '/plans/$planId/objectives/overview': typeof PlansPlanIdObjectivesOverviewRouteWithChildren
  '/plans/$planId/objectives/overview/$objectiveId': typeof PlansPlanIdObjectivesOverviewObjectiveIdRoute
  '/plans/$planId/objectives/overview/': typeof PlansPlanIdObjectivesOverviewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/plans/$planId'
    | '/plans'
    | '/plans/$planId/objectives'
    | '/plans/$planId/'
    | '/plans/$planId/objectives/$objectiveId'
    | '/plans/$planId/objectives/activity'
    | '/plans/$planId/objectives/analytics'
    | '/plans/$planId/objectives/overview'
    | '/plans/$planId/objectives/overview/$objectiveId'
    | '/plans/$planId/objectives/overview/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/plans'
    | '/plans/$planId/objectives'
    | '/plans/$planId'
    | '/plans/$planId/objectives/$objectiveId'
    | '/plans/$planId/objectives/activity'
    | '/plans/$planId/objectives/analytics'
    | '/plans/$planId/objectives/overview/$objectiveId'
    | '/plans/$planId/objectives/overview'
  id:
    | '__root__'
    | '/'
    | '/plans/$planId'
    | '/plans/'
    | '/plans/$planId/objectives'
    | '/plans/$planId/'
    | '/plans/$planId/objectives/$objectiveId'
    | '/plans/$planId/objectives/activity'
    | '/plans/$planId/objectives/analytics'
    | '/plans/$planId/objectives/overview'
    | '/plans/$planId/objectives/overview/$objectiveId'
    | '/plans/$planId/objectives/overview/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlansPlanIdRoute: typeof PlansPlanIdRouteWithChildren
  PlansIndexRoute: typeof PlansIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/': {
      id: '/plans/'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/$planId': {
      id: '/plans/$planId'
      path: '/plans/$planId'
      fullPath: '/plans/$planId'
      preLoaderRoute: typeof PlansPlanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/$planId/': {
      id: '/plans/$planId/'
      path: '/'
      fullPath: '/plans/$planId/'
      preLoaderRoute: typeof PlansPlanIdIndexRouteImport
      parentRoute: typeof PlansPlanIdRoute
    }
    '/plans/$planId/objectives': {
      id: '/plans/$planId/objectives'
      path: '/objectives'
      fullPath: '/plans/$planId/objectives'
      preLoaderRoute: typeof PlansPlanIdObjectivesRouteImport
      parentRoute: typeof PlansPlanIdRoute
    }
    '/plans/$planId/objectives/overview': {
      id: '/plans/$planId/objectives/overview'
      path: '/overview'
      fullPath: '/plans/$planId/objectives/overview'
      preLoaderRoute: typeof PlansPlanIdObjectivesOverviewRouteImport
      parentRoute: typeof PlansPlanIdObjectivesRoute
    }
    '/plans/$planId/objectives/analytics': {
      id: '/plans/$planId/objectives/analytics'
      path: '/analytics'
      fullPath: '/plans/$planId/objectives/analytics'
      preLoaderRoute: typeof PlansPlanIdObjectivesAnalyticsRouteImport
      parentRoute: typeof PlansPlanIdObjectivesRoute
    }
    '/plans/$planId/objectives/activity': {
      id: '/plans/$planId/objectives/activity'
      path: '/activity'
      fullPath: '/plans/$planId/objectives/activity'
      preLoaderRoute: typeof PlansPlanIdObjectivesActivityRouteImport
      parentRoute: typeof PlansPlanIdObjectivesRoute
    }
    '/plans/$planId/objectives/$objectiveId': {
      id: '/plans/$planId/objectives/$objectiveId'
      path: '/$objectiveId'
      fullPath: '/plans/$planId/objectives/$objectiveId'
      preLoaderRoute: typeof PlansPlanIdObjectivesObjectiveIdRouteImport
      parentRoute: typeof PlansPlanIdObjectivesRoute
    }
    '/plans/$planId/objectives/overview/': {
      id: '/plans/$planId/objectives/overview/'
      path: '/'
      fullPath: '/plans/$planId/objectives/overview/'
      preLoaderRoute: typeof PlansPlanIdObjectivesOverviewIndexRouteImport
      parentRoute: typeof PlansPlanIdObjectivesOverviewRoute
    }
    '/plans/$planId/objectives/overview/$objectiveId': {
      id: '/plans/$planId/objectives/overview/$objectiveId'
      path: '/$objectiveId'
      fullPath: '/plans/$planId/objectives/overview/$objectiveId'
      preLoaderRoute: typeof PlansPlanIdObjectivesOverviewObjectiveIdRouteImport
      parentRoute: typeof PlansPlanIdObjectivesOverviewRoute
    }
  }
}

interface PlansPlanIdObjectivesOverviewRouteChildren {
  PlansPlanIdObjectivesOverviewObjectiveIdRoute: typeof PlansPlanIdObjectivesOverviewObjectiveIdRoute
  PlansPlanIdObjectivesOverviewIndexRoute: typeof PlansPlanIdObjectivesOverviewIndexRoute
}

const PlansPlanIdObjectivesOverviewRouteChildren: PlansPlanIdObjectivesOverviewRouteChildren =
  {
    PlansPlanIdObjectivesOverviewObjectiveIdRoute:
      PlansPlanIdObjectivesOverviewObjectiveIdRoute,
    PlansPlanIdObjectivesOverviewIndexRoute:
      PlansPlanIdObjectivesOverviewIndexRoute,
  }

const PlansPlanIdObjectivesOverviewRouteWithChildren =
  PlansPlanIdObjectivesOverviewRoute._addFileChildren(
    PlansPlanIdObjectivesOverviewRouteChildren,
  )

interface PlansPlanIdObjectivesRouteChildren {
  PlansPlanIdObjectivesObjectiveIdRoute: typeof PlansPlanIdObjectivesObjectiveIdRoute
  PlansPlanIdObjectivesActivityRoute: typeof PlansPlanIdObjectivesActivityRoute
  PlansPlanIdObjectivesAnalyticsRoute: typeof PlansPlanIdObjectivesAnalyticsRoute
  PlansPlanIdObjectivesOverviewRoute: typeof PlansPlanIdObjectivesOverviewRouteWithChildren
}

const PlansPlanIdObjectivesRouteChildren: PlansPlanIdObjectivesRouteChildren = {
  PlansPlanIdObjectivesObjectiveIdRoute: PlansPlanIdObjectivesObjectiveIdRoute,
  PlansPlanIdObjectivesActivityRoute: PlansPlanIdObjectivesActivityRoute,
  PlansPlanIdObjectivesAnalyticsRoute: PlansPlanIdObjectivesAnalyticsRoute,
  PlansPlanIdObjectivesOverviewRoute:
    PlansPlanIdObjectivesOverviewRouteWithChildren,
}

const PlansPlanIdObjectivesRouteWithChildren =
  PlansPlanIdObjectivesRoute._addFileChildren(
    PlansPlanIdObjectivesRouteChildren,
  )

interface PlansPlanIdRouteChildren {
  PlansPlanIdObjectivesRoute: typeof PlansPlanIdObjectivesRouteWithChildren
  PlansPlanIdIndexRoute: typeof PlansPlanIdIndexRoute
}

const PlansPlanIdRouteChildren: PlansPlanIdRouteChildren = {
  PlansPlanIdObjectivesRoute: PlansPlanIdObjectivesRouteWithChildren,
  PlansPlanIdIndexRoute: PlansPlanIdIndexRoute,
}

const PlansPlanIdRouteWithChildren = PlansPlanIdRoute._addFileChildren(
  PlansPlanIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlansPlanIdRoute: PlansPlanIdRouteWithChildren,
  PlansIndexRoute: PlansIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
